insert into GENRES (NAME) values ('Alternative Rock');
insert into GENRES (NAME) values ('Ambient');
insert into GENRES (NAME) values ('Classical');
insert into GENRES (NAME) values ('Country');
insert into GENRES (NAME) values ('Dance & EDM');
insert into GENRES (NAME) values ('Dancehall');
insert into GENRES (NAME) values ('Deep House');
insert into GENRES (NAME) values ('Disco');
insert into GENRES (NAME) values ('Drum & Bass');
insert into GENRES (NAME) values ('Dubstep');
insert into GENRES (NAME) values ('Electronic');
insert into GENRES (NAME) values ('Folk & Singer-Songwriter');
insert into GENRES (NAME) values ('Hip-hop & Rap');
insert into GENRES (NAME) values ('House');
insert into GENRES (NAME) values ('Indie');
insert into GENRES (NAME) values ('Jazz & Blues');
insert into GENRES (NAME) values ('Latin');
insert into GENRES (NAME) values ('Metal');
insert into GENRES (NAME) values ('Piano');
insert into GENRES (NAME) values ('Pop');
insert into GENRES (NAME) values ('R&B & Soul');
insert into GENRES (NAME) values ('Reggae');
insert into GENRES (NAME) values ('Reggaeton');
insert into GENRES (NAME) values ('Rock');
insert into GENRES (NAME) values ('Soundtrack');
insert into GENRES (NAME) values ('Techno');
insert into GENRES (NAME) values ('Trance');
insert into GENRES (NAME) values ('Trap');
insert into GENRES (NAME) values ('Triphop');
insert into GENRES (NAME) values ('World');